---
name: Ygégé
version: "1.0.5"
slug: ygege
description: High-performance YGG Torrent indexer with automatic Cloudflare bypass
url: https://github.com/UwUDev/ygege
arch:
  - amd64
init: false
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  8715/tcp: 8715
ports_description:
  8715/tcp: Ygégé WEB UI and API
webui: "http://[HOST]:[PORT:8715]"
options:
  log_level: info
  imdb_enabled: true
  tmdb_enabled: true
  ygg_username: ""
  ygg_password: ""
schema:
  log_level: list(debug|info|warning|error)?
  imdb_enabled: bool?
  tmdb_enabled: bool?
  ygg_username: str?
  ygg_password: str?
environment:
  YGG_USERNAME: {{ ygg_username }}
  YGG_PASSWORD: {{ ygg_password }}